let ValidationError,DEBUG_MODE,CustomerrorHandler;_29c‍.x([["default",()=>_29c‍.o]]);_29c‍.w("joi",[["ValidationError",["ValidationError"],function(v){ValidationError=v}]]);_29c‍.w("../config",[["DEBUG_MODE",["DEBUG_MODE"],function(v){DEBUG_MODE=v}]]);_29c‍.w("../services/CustomerrorHandler",[["default",["CustomerrorHandler"],function(v){CustomerrorHandler=v}]]);



const errorHandler = (err, req, res, next) => {
  let statusCode = 500;
  let data = {
    message: "Internal server error",
    ...(DEBUG_MODE === "true" && { originalError: err.message }),
  };

  if (err instanceof ValidationError) {
      statusCode = 522,
      data = {
          message: err.message
      }
  }

  if (err instanceof CustomerrorHandler) {
      statusCode = err.status;
      data = {
          message: err.message
      }
  }

  return res.status(statusCode).json(data)
};

_29c‍.d(errorHandler);
